### ISSUE TITLE
Review notes on learning algorithms

### ISSUE THREAD

**Issue by Yuya-Furusawa** [QuantEcon/Games.jl#127]
@oyamad 
Please review the notes on learning algorithms([PR](https://github.com/QuantEcon/Games.jl/pull/115))
[Fictitious Play](https://nbviewer.jupyter.org/github/Yuya-Furusawa/game_theory_models/blob/feature/FictitiousPlay_Julia_note.ipynb)
[Local Interaction](https://nbviewer.jupyter.org/github/Yuya-Furusawa/game_theory_models/blob/feature/LocalInteraction_Julia.ipynb)
[Best Response Dynamics](https://nbviewer.jupyter.org/github/Yuya-Furusawa/game_theory_models/blob/feature/BestResponseDynamics_Julia.ipynb)
[Logit Response Dynamics](https://nbviewer.jupyter.org/github/Yuya-Furusawa/game_theory_models/blob/feature/logitdyn_julia.ipynb)

**Comment by MKobayashi23m** [comment]
I reviewed the notes. First, let me make some comments on  [Fictitious Play](https://nbviewer.jupyter.org/github/Yuya-Furusawa/game_theory_models/blob/feature/FictitiousPlay_Julia_note.ipynb).

In the first line, in the cell below the one with notations for strategy sets and others,
 “After each round of play, players observe the actual actions choosen by opponents, ...“
- "choosen” must be corrected as ‘chosen’.

In the cell next to the definition of the wight function,
“Each player assesses concerning the behavior of his opponents at each date and contingent on history”
- Though it is clarified in the next cell, it might be better if you write each player assesses what, as ‘assess’ is a transitive verb.

In the next cell,
- “hisopponents” →“his opponents” ?

In the cell that mentions the condition of the convergence of fictions play,
- I would like some basic explanation about what the potential game is, or reference to useful literature to learn about it.
- “IESDS” means “Iterative Elimination of Strictly Dominated Strategies”, I guess, but since this is the first use of this concept, it would be better for readers to write as “Iterative Elimination of Strictly Dominated Strategies (IESDS)”.

On the explanation of `play`,
The explanation says the `play` method “returns the new normalized actions history …” but it seems not. The displayed output looks like a mixed strategy profile and not a history.

“If you don't designate initial actions, they are choosed randomly.”
- “choosed” → “chosen”
- It might be good to write the distribution that the random draw of an initial play follows.

On the explanation of `time_series`,
- It would be better to explain what an argument `10` is (the length of the output series) though it can be inferred reading the contents below. 
- This might be a matter of taste, but as it looks similar to `num_reps` in `play`, for intuitive use, it might be better to put this argument after that of initial play. (So the command becomes `time_series(mp, (1,1)),10)`.  Similarly in the following stochastic fictitious play model.

On the explanation of the graph of the two-action simulation,
“… This result is consistent with manu papers.”
- “manu” → “many”?

On the explanation of the graph of the three-action-game simulation,
“… correspond to player's belief for opponent's first, second third action respectively”
- “first, second third action”→ “first, second and third”?

In the description of the Model of Stochastic Fictitious Play, 
“Almost all of the settings are same as original fictitious play model except for paerturbated payoff.”
→ “Almost all of the settings are the same as original fictitious play model except for perturbed payoff.” ?

“Note that we do not need to consider mixed startegies in this augmented game.”
- “startegies” → “strategies”
- Brief explanation for why it holds would be helpful for readers.

“…(i) two-player symmetric game with an interior ESS…”
- Clarifying what “ESS” refers to (I guess it would be Evolutionary Stable Strategies) would be helpful to readers. Brief explanation of the concept might also be helpful as this is the one that we might not learn in coremicroeconomics.

On “Stochastic Fictitious Play with constant gain” part,
- Explanation of the concept “risk-dominance” might be helpful.

**Comment by MKobayashi23m** [comment]
Please ignore unnecessary comments. I'm going to upload comment for the rest ASAP.

**Comment by Yuya-Furusawa** [comment]
@MKobayashi23m Thank you for the polite check!

We created another repository for the game theory notebooks.
https://github.com/QuantEcon/game-theory-notebooks
I'm sorry I forgot to contact you about this, and let's discuss here.

(I will close this issue after you check this comment)

**Comment by MKobayashi23m** [comment]
@Yuya-Furusawa 

Understood! Thank you. I will join in the repository.
