### ISSUE TITLE
Type stability

### ISSUE THREAD

**Issue by sglyon** [QuantEcon/Games.jl#2]
We have some minor type stability issues here. 

To see them try the following:

``` julia
using Games
g3 = NormalFormGame(randn(3,3,3,3))
@code_warntype payoff_vector(g3.players[1], (1, 2))
```

---

Also, we should be able to have inference work properly and not use `@generated` in the constructor with signature [`function NormalFormGame{T<:Real}(payoffs::Array{T})`](https://github.com/QuantEcon/Games.jl/blob/2630ff75aa0579f0b74819e4eb22516260ff7ec4/src/normal_form_game.jl#L421). Ping @StefanKarpinski if you have any ideas why inference wasn't working.

**Comment by oyamad** [comment]
Possibly related:

The `cournot` function in the notebook from [this PR](https://github.com/QuantEcon/QuantEcon.notebooks/pull/28#issue-140775523) is type-unstable and slow. I have a "generated" version along with the naive version from the notebook [here](http://nbviewer.jupyter.org/gist/oyamad/61f652caf3bb7eb57941).

**Comment by oyamad** [comment]
This is also type-unstable:

```julia
using Games
@code_warntype NormalFormGame(randn(2, 2))
```

**Comment by spencerlyon2** [comment]
Two more functions that cause a lot of type instability:

- `_reduce_last_player`: here we know that the output has one less dimension than the input. But the `reshape`s throw off inference
- `payoff_vector`: Here we know that the output is always a vector, but inference can't figure that out because of the `N-1` calls to `_reduce_last_player`

**Comment by StefanKarpinski** [comment]
Here's a version that doesn't use `@generated` but does use the `Cournot` type and is as fast:

```jl
function Base.call{N,T<:Real}(::Type{Cournot{N}},
                                         a::Real, c::Real, q_grid::Vector{T})
    nums_actions = tuple([length(q_grid) for i in 1:N]...)::NTuple{N,Int}
    S = promote_type(typeof(a), typeof(c), T)
    payoff_array= Array{T}(nums_actions)
    for I in CartesianRange(nums_actions)
        Q = zero(S)
        for i in 1:N
            Q += q_grid[I[i]]::T
        end
        payoff_array[I] = (a - c - Q) * q_grid[I[1]]
    end
    players = tuple([Player(payoff_array) for i in 1:N]...)::NTuple{N,Player{N,T}}
    return NormalFormGame(players)
end
```

**Comment by StefanKarpinski** [comment]
For the record, we tried removing both type assertions in the body and they were both necessary – type inference is not great at reasoning about generic N-d arrays and N-tuples.

**Comment by StefanKarpinski** [comment]
We also tried writing `ntuple(i->Player(payoff_array), N)` instead of `tuple([Player(payoff_array) for i in 1:N]...)` but that was substantially slower as well (might be worth filing a Julia perf bug, but maybe not since this tuple stuff is in heavy flux at the moment). In principle, the `ntuple` form should be easier for the compiler to reason about, but the actual `ntuple` construction seems to be slower.

**Comment by oyamad** [comment]
Regarding `payoff_vector` (https://github.com/QuantEcon/Games.jl/issues/2#issuecomment-197481488):

* We can change `_reduce_last_player` so that it always returns an `N`-dimensional array.

* The biggest problem is that the eltype of [`payoffs`](https://github.com/QuantEcon/Games.jl/blob/386bd09c63df546ead49497b8c6b065e7541373d/src/normal_form_game.jl#L93) is indeterminate.

  Maybe we should disallow

  ```jl
  typealias ActionProfile{T<:Real,N} NTuple{N,Action{T}}
  ```

  and restrict only to

  ```jl
  typealias PureActionProfile{N} NTuple{N,PureAction}
  typealias MixedActionProfile{T<:Real,N} NTuple{N,MixedAction{T}}
  ```
